### ISSUE TITLE
Alhaitham

### ISSUE THREAD

**Issue by satosoujirou** [thisRaptori/genshin-rotation-app#31]
alhaitham Q losing his dendro infusion after switching to kuki E, while in game it is possible to switch before u getting infusion and switch back fast to gain infusion from Q.

**Comment by thisRaptori** [comment]
Thanks for reporting!

I think this is the same as #3 ?

**Comment by satosoujirou** [comment]
oh yeah. i shouldve read before posting. sorry >.<

**Comment by thisRaptori** [comment]
No problem at all! Glad to have some eyes on it 😁 

I'll close this one for now in favour of that other one 👀
