### ISSUE TITLE
Feature Request for Burst swap

### ISSUE THREAD

**Issue by Maybe-a** [thisRaptori/genshin-rotation-app#33]
adding in Burst swap would allow for more accuracy when doing rotations for PC and mobile as there would be no action delay on a burst swap only Latency.

**Comment by Maybe-a** [comment]
its not swap latency as it is the action latency

swapping will have latency the same across all games but the action latency is non existent on swap bursts.

the slider is great for action latency but assuming 0 latency on all attacks is non accurate compared to no action latency on a Burst swap

**Comment by thisRaptori** [comment]
Ahh that makes sense, thanks!

**Comment by thisRaptori** [comment]
@Maybe-a this should be available now! Let me know if you have any issues with it and I'll reopen the issue 👍
